# Generated by Django 5.1 on 2024-11-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_category_pub_date_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique_for_date='pub_date', verbose_name='Слаг'),
        ),
    ]
